name: Run CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        flutter: [stable, beta, dev]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter }}
      - run: dart pub global activate dev_test
      # Run common validation test (analyzer, format, test) on your package (and nested packages)
      - run: dart pub global run dev_test:run_ci
